local M = {}

local function hi(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end

function M.setup(p)
  -- Editor UI
  hi("Normal",          { fg = p.fg,        bg = p.bg })
  hi("NormalFloat",     { fg = p.fg,        bg = p.bg_light })
  hi("NormalNC",        { fg = p.fg,        bg = p.bg_dark })
  hi("Cursor",          { fg = p.bg,        bg = p.fg })
  hi("CursorLine",      { bg = p.bg_light })
  hi("CursorLineNr",    { fg = p.purple,    bg = p.bg_light, bold = true })
  hi("LineNr",          { fg = p.comment })
  hi("SignColumn",      { fg = p.comment,   bg = p.bg })
  hi("ColorColumn",     { bg = p.bg_light })
  hi("VertSplit",       { fg = p.bg_lighter })
  hi("WinSeparator",    { fg = p.bg_lighter })
  hi("StatusLine",      { fg = p.fg,        bg = p.bg_dark })
  hi("StatusLineNC",    { fg = p.comment,   bg = p.bg_dark })
  hi("Pmenu",           { fg = p.fg,        bg = p.bg_light })
  hi("PmenuSel",        { fg = p.bg,        bg = p.purple })
  hi("PmenuSbar",       { bg = p.bg_lighter })
  hi("PmenuThumb",      { bg = p.purple })
  hi("Search",          { fg = p.bg,        bg = p.yellow })
  hi("IncSearch",       { fg = p.bg,        bg = p.orange })
  hi("CurSearch",       { fg = p.bg,        bg = p.orange })
  hi("Visual",          { bg = p.selection })
  hi("VisualNOS",       { bg = p.selection })
  hi("Folded",          { fg = p.comment,   bg = p.bg_light })
  hi("FoldColumn",      { fg = p.comment,   bg = p.bg })
  hi("MatchParen",      { fg = p.green,     bold = true,    underline = true })
  hi("ModeMsg",         { fg = p.green,     bold = true })
  hi("MoreMsg",         { fg = p.green })
  hi("Question",        { fg = p.pink })
  hi("ErrorMsg",        { fg = p.red })
  hi("WarningMsg",      { fg = p.orange })
  hi("NonText",         { fg = p.bg_lighter })
  hi("SpecialKey",      { fg = p.bg_lighter })
  hi("WildMenu",        { fg = p.bg,        bg = p.cyan })
  hi("TabLine",         { fg = p.comment,   bg = p.bg_dark })
  hi("TabLineSel",      { fg = p.fg,        bg = p.bg,      bold = true })
  hi("TabLineFill",     { bg = p.bg_dark })
  hi("EndOfBuffer",     { fg = p.bg_lighter })
  hi("Directory",       { fg = p.cyan })
  hi("Title",           { fg = p.purple,    bold = true })
  hi("Conceal",         { fg = p.comment })
  hi("SpellBad",        { undercurl = true, sp = p.red })
  hi("SpellCap",        { undercurl = true, sp = p.yellow })
  hi("SpellRare",       { undercurl = true, sp = p.cyan })
  hi("SpellLocal",      { undercurl = true, sp = p.pink })
  hi("QuickFixLine",    { bg = p.selection })

  -- Syntax (legacy)
  hi("Comment",         { fg = p.comment,   italic = true })
  hi("Constant",        { fg = p.purple })
  hi("String",          { fg = p.yellow })
  hi("Character",       { fg = p.green })
  hi("Number",          { fg = p.purple })
  hi("Boolean",         { fg = p.purple })
  hi("Float",           { fg = p.purple })
  hi("Identifier",      { fg = p.fg })
  hi("Function",        { fg = p.green })
  hi("Statement",       { fg = p.pink })
  hi("Conditional",     { fg = p.pink })
  hi("Repeat",          { fg = p.pink })
  hi("Label",           { fg = p.pink })
  hi("Operator",        { fg = p.pink })
  hi("Keyword",         { fg = p.pink,      italic = true })
  hi("Exception",       { fg = p.pink })
  hi("PreProc",         { fg = p.yellow })
  hi("Include",         { fg = p.pink })
  hi("Define",          { fg = p.pink })
  hi("Macro",           { fg = p.pink })
  hi("PreCondit",       { fg = p.pink })
  hi("Type",            { fg = p.cyan,      italic = true })
  hi("StorageClass",    { fg = p.pink })
  hi("Structure",       { fg = p.cyan })
  hi("Typedef",         { fg = p.cyan })
  hi("Special",         { fg = p.green })
  hi("Quote",           { link = "String" })
  hi("SpecialChar",     { fg = p.pink })
  hi("Tag",             { fg = p.cyan })
  hi("Delimiter",       { fg = p.fg })
  hi("SpecialComment",  { fg = p.comment,   italic = true })
  hi("Debug",           { fg = p.orange })
  hi("Underlined",      { underline = true })
  hi("Error",           { fg = p.red })
  hi("Todo",            { fg = p.bg,        bg = p.orange,  bold = true })

  -- Treesitter
  hi("@comment",              { link = "Comment" })
  hi("@comment.documentation",{ fg = p.comment, italic = true })
  hi("@string",               { link = "String" })
  hi("@string.delimiter",     { link = "String" })
  hi("@string.escape",        { fg = p.pink })
  hi("@string.special",       { fg = p.green })
  hi("@character",            { link = "Character" })
  hi("@number",               { link = "Number" })
  hi("@number.float",         { link = "Float" })
  hi("@boolean",              { link = "Boolean" })
  hi("@constant",             { fg = p.purple })
  hi("@constant.builtin",     { fg = p.purple,   italic = true })
  hi("@constant.macro",       { fg = p.purple })
  hi("@variable",             { fg = p.fg })
  hi("@variable.builtin",     { fg = p.purple,   italic = true })
  hi("@variable.parameter",   { fg = p.orange })
  hi("@variable.member",      { fg = p.fg })
  hi("@function",             { fg = p.green })
  hi("@function.builtin",     { fg = p.cyan })
  hi("@function.call",        { fg = p.green })
  hi("@function.macro",       { fg = p.green })
  hi("@function.method",      { fg = p.green })
  hi("@function.method.call", { fg = p.green })
  hi("@constructor",          { fg = p.cyan })
  hi("@keyword",              { fg = p.pink,     italic = true })
  hi("@keyword.function",     { fg = p.pink,     italic = true })
  hi("@keyword.operator",     { fg = p.pink })
  hi("@keyword.return",       { fg = p.pink,     italic = true })
  hi("@keyword.import",       { fg = p.pink })
  hi("@keyword.conditional",  { fg = p.pink })
  hi("@keyword.repeat",       { fg = p.pink })
  hi("@keyword.exception",    { fg = p.pink })
  hi("@operator",             { fg = p.pink })
  hi("@punctuation.bracket",  { fg = p.fg })
  hi("@punctuation.delimiter",{ fg = p.fg })
  hi("@punctuation.special",  { fg = p.pink })
  hi("@type",                 { fg = p.cyan,     italic = true })
  hi("@type.builtin",         { fg = p.cyan,     italic = true })
  hi("@type.definition",      { fg = p.cyan })
  hi("@attribute",            { fg = p.green })
  hi("@property",             { fg = p.fg })
  hi("@field",                { fg = p.fg })
  hi("@tag",                  { fg = p.pink })
  hi("@tag.attribute",        { fg = p.yellow })
  hi("@tag.delimiter",        { fg = p.fg })
  hi("@namespace",            { fg = p.cyan })
  hi("@module",               { fg = p.cyan })
  hi("@label",                { fg = p.pink })
  hi("@text",                 { fg = p.fg })
  hi("@markup.strong",        { bold = true })
  hi("@markup.italic",        { italic = true })
  hi("@markup.underline",     { underline = true })
  hi("@markup.heading",       { fg = p.purple,   bold = true })
  hi("@markup.link",          { fg = p.cyan,     underline = true })
  hi("@markup.link.url",      { fg = p.cyan,     underline = true })
  hi("@markup.raw",           { fg = p.green })
  hi("@markup.list",          { fg = p.pink })
  hi("@diff.plus",            { fg = p.green })
  hi("@diff.minus",           { fg = p.red })
  hi("@diff.delta",           { fg = p.orange })

  -- Diagnostics
  hi("DiagnosticError",            { fg = p.red })
  hi("DiagnosticWarn",             { fg = p.orange })
  hi("DiagnosticInfo",             { fg = p.cyan })
  hi("DiagnosticHint",             { fg = p.green })
  hi("DiagnosticUnnecessary",      { fg = p.comment })
  hi("DiagnosticUnderlineError",   { undercurl = true, sp = p.red })
  hi("DiagnosticUnderlineWarn",    { undercurl = true, sp = p.orange })
  hi("DiagnosticUnderlineInfo",    { undercurl = true, sp = p.cyan })
  hi("DiagnosticUnderlineHint",    { undercurl = true, sp = p.green })
  hi("DiagnosticVirtualTextError", { fg = p.red,    italic = true })
  hi("DiagnosticVirtualTextWarn",  { fg = p.orange, italic = true })
  hi("DiagnosticVirtualTextInfo",  { fg = p.cyan,   italic = true })
  hi("DiagnosticVirtualTextHint",  { fg = p.green,  italic = true })
  hi("DiagnosticSignError",        { fg = p.red })
  hi("DiagnosticSignWarn",         { fg = p.orange })
  hi("DiagnosticSignInfo",         { fg = p.cyan })
  hi("DiagnosticSignHint",         { fg = p.green })

  -- LSP
  hi("LspReferenceText",   { bg = p.selection })
  hi("LspReferenceRead",   { bg = p.selection })
  hi("LspReferenceWrite",  { bg = p.selection, underline = true })
  hi("LspSignatureActiveParameter", { fg = p.cyan, bold = true })

  -- Diff
  hi("DiffAdd",     { fg = p.green,  bg = p.bg_light })
  hi("DiffChange",  { fg = p.orange, bg = p.bg_light })
  hi("DiffDelete",  { fg = p.red,    bg = p.bg_light })
  hi("DiffText",    { fg = p.orange, bg = p.selection })
  hi("diffAdded",   { fg = p.green })
  hi("diffRemoved", { fg = p.red })
  hi("diffChanged", { fg = p.orange })
  hi("diffFile",    { fg = p.cyan })
  hi("diffNewFile", { fg = p.green })
  hi("diffLine",    { fg = p.comment })

  -- Telescope
  hi("TelescopeBorder",         { fg = p.comment,  bg = p.bg_light })
  hi("TelescopeNormal",         { fg = p.fg,        bg = p.bg_light })
  hi("TelescopePromptBorder",   { fg = p.purple,    bg = p.bg_light })
  hi("TelescopePromptNormal",   { fg = p.fg,        bg = p.bg_light })
  hi("TelescopePromptPrefix",   { fg = p.pink })
  hi("TelescopeResultsBorder",  { fg = p.comment,  bg = p.bg_light })
  hi("TelescopePreviewBorder",  { fg = p.comment,  bg = p.bg_light })
  hi("TelescopeMatching",       { fg = p.cyan,      bold = true })
  hi("TelescopeSelection",      { fg = p.fg,        bg = p.selection })
  hi("TelescopeSelectionCaret", { fg = p.pink,      bg = p.selection })
  hi("TelescopeMultiSelection", { fg = p.purple })
  hi("TelescopeTitle",          { fg = p.pink,      bold = true })

  -- NeoTree
  hi("NeoTreeNormal",           { fg = p.fg,       bg = p.bg_dark })
  hi("NeoTreeNormalNC",         { fg = p.fg,       bg = p.bg_dark })
  hi("NeoTreeEndOfBuffer",      { fg = p.bg_dark,  bg = p.bg_dark })
  hi("NeoTreeIndentMarker",     { fg = p.bg_lighter })
  hi("NeoTreeRootName",         { fg = p.purple,   bold = true })
  hi("NeoTreeFileName",         { fg = p.fg })
  hi("NeoTreeFileIcon",         { fg = p.cyan })
  hi("NeoTreeDirectoryIcon",    { fg = p.cyan })
  hi("NeoTreeDirectoryName",    { fg = p.cyan })
  hi("NeoTreeSymlinkTarget",    { fg = p.pink })
  hi("NeoTreeGitAdded",         { fg = p.green })
  hi("NeoTreeGitModified",      { fg = p.orange })
  hi("NeoTreeGitDeleted",       { fg = p.red })
  hi("NeoTreeGitUntracked",     { fg = p.comment })
  hi("NeoTreeGitConflict",      { fg = p.red,      bold = true })
  hi("NeoTreeGitIgnored",       { fg = p.comment })
  hi("NeoTreeGitStaged",        { fg = p.green })
  hi("NeoTreeFloatBorder",      { fg = p.purple })
  hi("NeoTreeFloatTitle",       { fg = p.purple,   bold = true })
  hi("NeoTreeTitleBar",         { fg = p.bg,       bg = p.purple })
  hi("NeoTreeFilterTerm",       { fg = p.green,    bold = true })
  hi("NeoTreeDotfile",          { fg = p.comment })
  hi("NeoTreeHiddenByName",     { fg = p.comment })
  hi("NeoTreeStatusLine",       { fg = p.comment,  bg = p.bg_dark })
  hi("NeoTreeStatusLineNC",     { fg = p.comment,  bg = p.bg_dark })

  -- Gitsigns
  hi("GitSignsAdd",       { fg = p.green })
  hi("GitSignsChange",    { fg = p.orange })
  hi("GitSignsDelete",    { fg = p.red })
  hi("GitSignsAddNr",     { fg = p.green })
  hi("GitSignsChangeNr",  { fg = p.orange })
  hi("GitSignsDeleteNr",  { fg = p.red })
  hi("GitSignsAddLn",     { bg = p.bg_light })
  hi("GitSignsChangeLn",  { bg = p.bg_light })
  hi("GitSignsCurrentLineBlame", { fg = p.comment, italic = true })

  -- nvim-cmp
  hi("CmpItemAbbr",           { fg = p.fg })
  hi("CmpItemAbbrDeprecated", { fg = p.comment,  strikethrough = true })
  hi("CmpItemAbbrMatch",      { fg = p.cyan,     bold = true })
  hi("CmpItemAbbrMatchFuzzy", { fg = p.cyan })
  hi("CmpItemKind",           { fg = p.purple })
  hi("CmpItemMenu",           { fg = p.comment })
  hi("CmpItemKindFunction",   { fg = p.green })
  hi("CmpItemKindMethod",     { fg = p.green })
  hi("CmpItemKindConstructor",{ fg = p.cyan })
  hi("CmpItemKindField",      { fg = p.fg })
  hi("CmpItemKindVariable",   { fg = p.fg })
  hi("CmpItemKindClass",      { fg = p.cyan })
  hi("CmpItemKindInterface",  { fg = p.cyan })
  hi("CmpItemKindModule",     { fg = p.cyan })
  hi("CmpItemKindProperty",   { fg = p.fg })
  hi("CmpItemKindKeyword",    { fg = p.pink })
  hi("CmpItemKindText",       { fg = p.fg })
  hi("CmpItemKindEnum",       { fg = p.orange })
  hi("CmpItemKindEnumMember", { fg = p.orange })
  hi("CmpItemKindConstant",   { fg = p.purple })
  hi("CmpItemKindSnippet",    { fg = p.yellow })
  hi("CmpItemKindColor",      { fg = p.pink })

  -- WhichKey
  hi("WhichKey",          { fg = p.pink })
  hi("WhichKeyGroup",     { fg = p.purple })
  hi("WhichKeyDesc",      { fg = p.cyan })
  hi("WhichKeySeparator", { fg = p.comment })
  hi("WhichKeyFloat",     { bg = p.bg_dark })
  hi("WhichKeyBorder",    { fg = p.comment })
  hi("WhichKeyValue",     { fg = p.comment })

  -- illuminate
  hi("IlluminatedWordText",  { bg = p.selection })
  hi("IlluminatedWordRead",  { bg = p.selection })
  hi("IlluminatedWordWrite", { bg = p.selection, underline = true })

  -- Lazy
  hi("LazyButton",             { fg = p.fg,     bg = p.bg_lighter })
  hi("LazyButtonActive",       { fg = p.bg,     bg = p.purple, bold = true })
  hi("LazyH1",                 { fg = p.bg,     bg = p.purple, bold = true })
  hi("LazyH2",                 { fg = p.purple, bold = true })
  hi("LazySpecial",            { fg = p.cyan })
  hi("LazyProgressDone",       { fg = p.green })
  hi("LazyProgressTodo",       { fg = p.comment })
  hi("LazyNormal",             { fg = p.fg,     bg = p.bg_light })
  hi("LazyComment",            { fg = p.comment })
  hi("LazyProp",               { fg = p.cyan })
  hi("LazyValue",              { fg = p.yellow })
  hi("LazyReasonPlugin",       { fg = p.purple })
  hi("LazyReasonEvent",        { fg = p.orange })
  hi("LazyReasonCmd",          { fg = p.pink })
  hi("LazyReasonFt",           { fg = p.cyan })
  hi("LazyReasonKeys",         { fg = p.green })
  hi("LazyReasonSource",       { fg = p.yellow })
  hi("LazyReasonRuntime",      { fg = p.red })

  -- Flash
  hi("FlashBackdrop",   { fg = p.comment })
  hi("FlashMatch",      { fg = p.cyan,   bg = p.bg_lighter, bold = true })
  hi("FlashCurrent",    { fg = p.orange, bg = p.bg_lighter, bold = true })
  hi("FlashLabel",      { fg = p.bg,     bg = p.pink,       bold = true })
  hi("FlashPrompt",     { fg = p.pink })
  hi("FlashCursor",     { fg = p.bg,     bg = p.pink })

  -- Mason
  hi("MasonHeader",                  { fg = p.bg,     bg = p.pink,   bold = true })
  hi("MasonHeaderSecondary",         { fg = p.bg,     bg = p.green,  bold = true })
  hi("MasonHighlight",               { fg = p.cyan })
  hi("MasonHighlightBlock",          { fg = p.bg,     bg = p.cyan })
  hi("MasonHighlightBlockBold",      { fg = p.bg,     bg = p.cyan,   bold = true })
  hi("MasonHighlightSecondary",      { fg = p.yellow })
  hi("MasonHighlightBlockSecondary", { fg = p.bg,     bg = p.yellow })
  hi("MasonHighlightBlockBoldSecondary", { fg = p.bg, bg = p.yellow, bold = true })
  hi("MasonMuted",                   { fg = p.comment })
  hi("MasonMutedBlock",              { fg = p.fg,     bg = p.bg_lighter })
  hi("MasonError",                   { fg = p.red })
  hi("MasonWarning",                 { fg = p.orange })
end

function M.lualine_theme(p)
  local c = {
    normal   = p.purple,
    insert   = p.green,
    visual   = p.pink,
    replace  = p.red,
    command  = p.orange,
    inactive = p.comment,
  }
  local function mode_section(color)
    return { a = { fg = p.bg, bg = color, gui = "bold" }, b = { fg = p.fg, bg = p.bg_lighter }, c = { fg = p.comment, bg = p.bg_dark } }
  end
  return {
    normal   = mode_section(c.normal),
    insert   = mode_section(c.insert),
    visual   = mode_section(c.visual),
    replace  = mode_section(c.replace),
    command  = mode_section(c.command),
    inactive = { a = { fg = c.inactive, bg = p.bg_dark }, b = { fg = c.inactive, bg = p.bg_dark }, c = { fg = c.inactive, bg = p.bg_dark } },
  }
end

return M
